### PR TITLE
add 23-basedelay test

### PR DESCRIPTION
**Pull request by selhammer**
Signed-off-by: Anders Selhammer anders.selhammer@est.tech

### CODE REVIEW

**Comment by mlichvar** [comment]
The commit says "add 23-basedelayvariation test", but it adds a new test and modifies an existing test. Maybe it would be better to add two new tests?

I'd suggest to name the new test 23-basedelay.

**Comment by selhammer** [comment]
ok, I can rename the TC and then remove the updates in TC 11 rather than adding a new TC. This new test case would not gain more than it cost to run. 
Sync and delay rate are related and this TC11 is not fully correct since the sync rate are less than delay rate at start which is not how it should be according to the standard, therefore I updated it.

Ok, How do I do this in an easy way to avoid several commits. If I push directly to GitHub I can just change the push but since a compared this to an existing branch, I need to add a second commit in my branch and will that not end up in two new commits in your repo, instead of one?

**Comment by mlichvar** [comment]
You can rebase the commits and force push the your branch, which should show as a new set of commits here. There should be no problem with duplicated commits.

**Comment by selhammer** [comment]
Nice, I did not know it would end up in same commit but now it is updated

**Comment by mlichvar** [comment]
Thanks!

**Pull request merged**
